#!/bin/bash
HOST_IP=${HOST_IP:-"0.0.0.0"}
HOST_PUBLIC_API_PORT=${HOST_PUBLIC_API_PORT:-"8200"}
SIMPLE_CONFIG_PATH=${SIMPLE_CONFIG_PATH:-"config.toml"}
SIMPLE_DB_PATH=${SIMPLE_DB_PATH:-"data/db"}
SIMPLE_BIN=${1:-$SIMPLE_BIN}

# Runs command
ls ./ -al
$SIMPLE_BIN run --node-config $SIMPLE_CONFIG_PATH --db-path $SIMPLE_DB_PATH --public-api-address $HOST_IP:$HOST_PUBLIC_API_PORT
